import os
import json
import pickle
import random
import numpy as np
import nltk
from flask import Flask, render_template, request
from nltk.stem import LancasterStemmer

# Create a clear path
nltk_data_path = os.path.join(os.getcwd(), 'nltk_data')
if not os.path.exists(nltk_data_path):
    os.makedirs(nltk_data_path)
nltk.data.path.append(nltk_data_path)

# Download everything needed for tokenization
nltk.download('punkt', download_dir=nltk_data_path, quiet=True)
nltk.download('punkt_tab', download_dir=nltk_data_path, quiet=True)

app = Flask(__name__)
stemmer = LancasterStemmer()

# --- 2. LOAD THE AI BRAIN ---
# Loading the files generated by train.py
try:
    words = pickle.load(open("words.pkl", "rb"))
    classes = pickle.load(open("classes.pkl", "rb"))
    model = pickle.load(open("chatbot_model.pkl", "rb"))
    with open("intents.json") as file:
        intents = json.load(file)
except Exception as e:
    print(f"Error loading model files: {e}")

# --- 3. HELPER FUNCTIONS ---
def clean_up_sentence(sentence):
    sentence_words = nltk.word_tokenize(sentence)
    sentence_words = [stemmer.stem(word.lower()) for word in sentence_words]
    return sentence_words

def bow(sentence, words):
    sentence_words = clean_up_sentence(sentence)
    bag = [0] * len(words)
    for s in sentence_words:
        for i, w in enumerate(words):
            if w == s:
                bag[i] = 1
    return np.array(bag).reshape(1, -1)

# --- 4. WEB ROUTES ---

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/get")
def get_bot_response():
    userText = request.args.get('msg')
    
    # Predict the intent
    results = model.predict(bow(userText, words))
    tag = results[0]
    
    # Find response from intents.json
    response = "I'm sorry, I don't understand that. Can you rephrase?"
    for i in intents['intents']:
        if i['tag'] == tag:
            response = random.choice(i['responses'])
            break
            
    return str(response)

# --- 5. CLOUD DEPLOYMENT PORT FIX ---
if __name__ == "__main__":
    # Render sets a 'PORT' environment variable automatically
    port = int(os.environ.get("PORT", 5000))
    # host='0.0.0.0' is required for the cloud to access the app
    app.run(host='0.0.0.0', port=port)